

services:
  postgres1:
    image: postgres:latest
    environment:
      POSTGRES_DB: test2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 3cure
    ports:
      - "5432:5432"
    networks:
      - pgverse1
    volumes:
      - pg_data:/var/lib/postgresql/data

  pgadmin1:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.ir
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres1
    networks:
      - pgverse1
    volumes:
      - pgadmin_data:/var/lib/pgadmin

networks:
  pgverse1:
  
volumes:
  pg_data:
  pgadmin_data:

